# Generated by Django 4.2.20 on 2025-04-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0015_attendancerange"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendanceclass",
            options={"verbose_name": "Attendance", "verbose_name_plural": "Attendance"},
        ),
    ]
